### ISSUE TITLE
Unable to scale down the BBBECSStack in autoscaling group

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#10] opened 2020-09-24 12:38 UTC
When we launch BBB through cloudformation template, it create BBBAppStack with 1 max and 1 desired server, BBBECSStack with 10 max and 6 desired server, and BBBTurnStack.

If we try to change the desired server to 1 in BBBECSStack, then after 1-2 minutes it automatically scales up to 6 -10 server without any traffic. What can be its resolution?

**Comment by couchgott** [comment] 2020-09-24 12:43
Hi, 

this is caused by the Scaling Targets from the ECS tasks and the Capacity provider. 

We're already working on a fix for the unexpected scale-out.

**Comment by couchgott** [comment] 2020-09-24 12:45
Duplicate of #5

**Closed by couchgott** 2020-09-24 12:45 UTC
