### ISSUE TITLE
Running step-by-step script not working

### ISSUE THREAD

**Issue by ElieNahas** [aws-samples/aws-scalable-big-blue-button-example#114] opened 2022-05-27 12:14 UTC
**Description**
I am running the step-by-step script to deploy BBB. When it comes to deploying the "BBBgreenlightService", it takes a lot of time to execute. After few hours, I receive the following error: The following resource(s) failed to create: [BBBScaleliteService, BBBgreenlightService].

When I was checking the tasks in the clusters, all the tasks are in "Stopped" status during creation.
InternalError: failed to normalize image reference "/blindsidenetwks/scalelite:v1-api"
InternalError: failed to normalize image reference "/bigbluebutton/greenlight:v2"
InternalError: failed to normalize image reference "/blindsidenetwks/scalelite:v1-nginx"

**Screenshots**
<img width="1145" alt="Cluster task error list" src="https://user-images.githubusercontent.com/19953015/170696935-dc56628b-0574-483e-8845-44c6e3f8789d.png">

<img width="1440" alt="Cluster task error detaills" src="https://user-images.githubusercontent.com/19953015/170697103-9c175ebf-d370-4b1d-8d8f-7f3614c099b3.png">

**Comment by couchgott** [comment] 2022-05-27 13:41
Hey @ElieNahas 

can you please revisit the prerequisites section of the readme and ensure you have everything in place. 
i guess docker is missing locally. 

best,

David

**Comment by ElieNahas** [comment] 2022-05-27 14:21
Hello Dave,

Thank you for your reply.

I have checked the readme file and I made sure to have everything configured and in place:
- bash
- aws-cli
- jq
- docker
- a valid Route53 Hosted Zone
- valid email addresses

Concerning Docker, I have docker installed on my Mac and it contains the images of BBB.

For the manual script, it was stuck on the following: The following resource(s) failed to create: [BBBScaleliteService, BBBgreenlightService].

And, I tried also to run the automated script, I was receiving the following error: The following resource(s) failed to create: [BBBSESProvider]. Knowing that I have configured manually the email address in SES and even tried to set the BBBSESValidated flag to true and false but did not solve the issue. 
NB: I am using a Gmail address not an email that belongs to the domain where I am deploying the solution.

I have been trying to solve the issue for the previous 2 days and I checked the previous questions/bugs and tried multiple solutions but nothing worked.

Any additional guidance to unblock the situation would be appreciated.

Thank you.

**Comment by couchgott** [comment] 2022-05-27 14:47
for me it looks like sth is wrong with the image path it should look like: 

[ACCOUNTID].dkr.ecr.[REGION].amazonaws.com/bigbluebutton/greenlight:v2
(or like with scalelite:1)

can you check in ECR if the images ended up there?
Also from the cloudformation stack, can you post the related events.

cheers,

David

**Comment by ElieNahas** [comment] 2022-05-27 15:00
After running the **automated** script for 2-3min, in the terminal I am receiving the following when it comes to validating the docker images:
Error parsing reference: "[ACCOUNTID].dkr.ecr..amazonaws.com/bigbluebutton/greenlight:v2" is not a valid repository/tag: invalid reference format

The region field is empty. Knowing that I have a default one selected in AWS CLI. As a first step, can you assist me on how to fix the region to see if it will unblock the situation?

Thank you

**Comment by couchgott** [comment] 2022-05-27 15:45
hmm... 

which region do you use?

**Comment by ElieNahas** [comment] 2022-05-27 15:46
eu-west-3

**Comment by ElieNahas** [comment] 2022-05-27 15:49
Knowing that the ECR created on AWS has a region while in the terminal when attempting to parse the docker the region is empty
<img width="1102" alt="Screen Shot 2022-05-27 at 6 47 29 PM" src="https://user-images.githubusercontent.com/19953015/170734348-b5f7993e-5074-4c44-8e2c-d42e6bb872b1.png">

**Comment by couchgott** [comment] 2022-05-27 15:51
ok. so that should not cause the issue .. 

so can you set the reguion manually before starting the script 
AWS_Region=eu-west-3 

maybe the issue is somewhere here at the setup.sh


  if [[ -z "${AWS_REGION}" ]]; then
    REGION=$(aws configure get region --profile=$BBBPROFILE)
    echo "Using default region ${REGION} from profile ${BBBPROFILE}"
  else
    REGION=${AWS_REGION}
    echo "Using region ${REGION} from AWS_REGION environment variable"
  fi

alternatively please set the region for the profile you're using explicit

**Comment by ElieNahas** [comment] 2022-05-27 19:38
Changing the script manually and forcing the region allowed me to update the Docker files to AWS. But I am still receiving an error while running the automated script related to BBBSESProvider:

The following resource(s) failed to create: [BBBSESProvider].

Resource handler returned message: "1 validation error detected: Value 'bbbtestingmeetexample2-BBBSESProviderStack-YJMMWXISB7IN-ses-provider' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: Lambda, Status Code: 400, Request ID: a42379dd-cf41-4a13-86de-8324a73a83eb)" (RequestToken: 09107524-cf32-5cf4-3b1e-c49daddd6396, HandlerErrorCode: InvalidRequest)

**Comment by couchgott** [comment] 2022-05-28 07:39
can you please double check if the hosted domain is setup properly and reachable from public. 
also, please check also if there is already that domain setup at SES (it should not, if you did not set the parameter to pre-validated for SES)

**Comment by ElieNahas** [comment] 2022-05-28 13:41
Hello,

What caused the issue was the name of the function generated is too long. So I had to re-run the script by using a shorter name from my end for the stack name which solved the issue. 

The script was successfully completed and the servers are up and running. Thank you for your help.

I had an issue when trying to log in using the generated admin credentials. I checked the closed ticket that fixed the bug. But I have a question related to that, in case one of the files in the scripts and templates folder has changed, do I need to only re-run the automated script which will update the changes? If not what are the steps that should I do to update the changes?

**Comment by ElieNahas** [comment] 2022-05-30 18:12
Hello @couchgott ,

Thank you for your time and help.
I have 2 additional questions related to the script and configuration.  

**Question 1:**
I had an issue when trying to log in using the generated admin credentials. I checked the closed ticket that fixed the bug. But I have a question related to that, in case one of the files in the scripts and templates folder has changed, do I need to only re-run the automated script which will update the changes? If not what are the steps that should I do to update the changes?

**Question 2:**
I need to access the BBB server from the terminal using SSH to adjust some files and configurations related to design/routings and other files. I tried multiple combinations but with no success. Where can I retrieve the credentials (username and password of the AMI user generated from the script) to access the EC2 server?

**Comment by Mitcal** [comment] 2022-05-30 20:18
Hi @ElieNahas,
I hope you don't mind if I stick my oar in here... I don't know how to answer Q1 but I have had to connect to the EC2 servers myself (Q2). Not that I would really advise changing the servers directly unless you a) never plan to do an update and b) don't want to replicate the servers. If you plan to do either of these things then you should modify the startup scripts instead (in the code base). That way any updates/changes you can keep track of much more easily... 
Having said all of that, if you do want to SSH into the servers. You need to get the private key file and then use something like `ssh ec2user@111.222.333.444 -i path/to/private-keyfile.pem`
In my case the server was not spinning up with an associated private key. I had to instruct the ec2 spinner-upper to use my private key file. (I think Auto-Scaling Group may be the correct technical term... or it might have been the Load Balancer, I'm afraid I don't recall exactly but I hope that still helps.)

**Comment by couchgott** [comment] 2022-06-01 06:17
to clarify. 
2) if you alter locally you most likely loose the option to use the setup (semi-)auto-scaling. as next instance bootstrapped will pretty much not have your config. 
as @Mitcal mentioned, fork the repo. clone it locally. create a new branch for your changes. 
then alter what you need within the bootstraping section of the appserver template. place files (like logo files) into the scripts folder for instance and then you can grab the file from the bootstrap s3 as sideload. 
this will make it robust to failures and scaling
About SSH: there is no key on the instance. you can change that using the launch template settings and redeploy the instance (see comment before) or. Better option. use the SSM Session manager. Go to EC2, select instance, hit connect at the top menu. choose session manager. 
that's the "official" way we choosed as this eliminates the need to expose port 22 or any ssh to public. 

about 1) 
in case you deployed before the fix has  been released you might want to destroy/redeploy the whole stack to also include other breaking changes before heading to further work 
OR
you can alter the admin password at secrets manager manually. empty the RDS database. goto ECS and kill the greenlight task (it will restart) and let greenlight bootstrap from scratch

hope this helps,

best

**Comment by ElieNahas** [comment] 2022-06-02 06:33
Hello @Mitcal and @couchgott ,

Thank you for your reply and for clarifying my questions.

Concerning the first question, I will try to destroy the instance and re-run it to see if it will solve the issue.

And for the second question, I will do my research on how to configure the BBB dynamically from the scripts when deploying the instance. Meanwhile, I tried to unblock the situation by accessing the server via SSH but I was not able to even after trying multiple credentials and trying multiple workarounds to authenticate. But as @couchgott mentioned I was able to connect to the server using SSM Session manager.

**Comment by ElieNahas** [comment] 2022-06-02 06:40
My main objective is not to use the Greenlight UI to access BBB. We have our own UI integrated with our LMS platform to manage the calls/recordings/administration. We mainly use the BBB APIs to handle all the user requests. For that, I have multiple questions about the following.

**Question: Recordings disk storage scale**
We mainly have been using an old version of the BBB deployed on Azure and now we are migrating into version 2.4.7 on AWS. This project solves a lot of problems that we have encountered mainly related to scalability. We have existing recordings of around 300GB on our old servers and we will be moving them into this project. Which configuration file in the scripts should we modify to specify the disk storage allocated for recordings? We will need a disk with around 1TB of storage.

I tried to modify the BBBApplicationDataVolumeSize to 100GB (for testing) but it is not clear where the recordings are being saved. What does 8.0E disk storage mean? Kindly find attached a screenshot of the disks. 
127.0.0.1:/     8.0E  1.0M  8.0E   1%  /mnt/bbb-recordings


<img width="598" alt="disk-storage" src="https://user-images.githubusercontent.com/19953015/171568034-9b307b0a-b429-42f3-89b4-fa8e5032e67d.png">

**Comment by Mitcal** [comment] 2022-06-02 09:36
Hi @ElieNahas,
I also set this up for similar reasons, using it with our LMS (Moodle). It works very well with the available plugins for Moodle.

I believe that all of the recordings are stored on an attached EFS volume which will be mounted on boot up of the EC2 instance. This volume is "Elastic" so doesn't need to be partitioned or allocated a specific amount of storage. It will keep growing almost forever and you will be billed for the amount of storage space you use. 

I'm pretty sure the BBBApplicationDataVolumeSize will set the site of the EBS volume for each EC2 Application Instance. This is only for transitory data while recordings are being processed and before they are stored in the EFS file system. It's not for persistent storage.

I've never had to move recordings from another system, but I'm sure it's possible. You could probably upload the files via your SSH connection. You would probably also need to move the database entries as well.

I hope that helps a little bit. I'm not the expert (like Dave) but I have some experience, so thought I should try and help.

**Comment by couchgott** [comment] 2022-06-02 14:36
Hey, 

yes the BBBApplicationDataVolumeSize Parameter is affecting the local recording data volume of each BBB Application instance where records are persistent until they have been moved to the central (EFS Based) Recordings store. 
So during the meeting the recording is saved locally. then encoded, then moved to the central data store where it can be accessed by the frontend indipendend from the original application instance. 

if you want to migrate from your old system it should be placed onto the EFS i think. 
is it possible to migrate from another BBB to this "scalable" setup ... i honestly do not know. try it out ;) 

to access the central storage you can do as follows:
boot up an EC2 as bastian/admin host. give it the right instance profile and allow it's security group to access the EFS file mounts via the EFS Mount target Security Group. 

that would be a clean way todo so. 
not sure where your old setup  is located but depending where you can either use for an external source e.g. S3 as file exchange, open SSH to the bastion or ssh from the bastion to the source system. 
the S3 file exchange utilizing e.g. the aws cli might have to pro that you can do multi-path uploads which will speed up the process. SSH as file transfer tool is rather slow.

**Comment by ElieNahas** [comment] 2022-06-03 13:50
Hello @Mitcal and @couchgott ,

Based on the discussion, if the above is the case (using the EFS) then this will solve the issue of all-new recordings generated on this scalable new server without allocating specific disk storage.

Concerning the migration of recordings from an old BBB server into a new one, is applicable and doable from one instance to another. This is mentioned in the following [link](https://docs.bigbluebutton.org/admin/customize.html#transfer-published-recordings-from-another-server). 

In our case here, we are transferring the recordings from the old BBB server (single instance) into this BBB server where we are using Scalelite and load balancers to manage the scalability and distribute the recordings into EFS, not the local EC2 disk.
Do you have any idea on how to do that or where should we move the files on the new server? Is it on into the local disk until distributed into the EFS? or directly into the mounted EFS storage?

Reference related to Scalelite recording: [link](https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md)

**Comment by Mitcal** [comment] 2022-06-04 11:02
Hi @ElieNahas ,
This is probably where you have to get a bit creative, because it sounds like there isn't a standard procedure for this.
I think what Dave is suggesting is to use an S3 bucket on your AWS account as a file transfer. So I guess it would go something like this:
- Create an S3 bucket for uploading your recordings from your old server and upload them using one of the channels in to s3 (such as AWS CLI : https://adamtheautomator.com/upload-file-to-s3).
- While you upload your 300G of recordings, create a new EC2 instance which can connect to your S3 storage, SSH into it and mount your EFS disk (the one which is used for the BBB recordings). https://docs.aws.amazon.com/efs/latest/ug/wt1-test.html
- Install the AWS CLI on the new EC2 instance and use the cp command for transferring the files from S3 to the mounted EFS drive for the BBB recordings.
I hope that makes sense, and that I've got it right ;-). 
Best, Michael

**Comment by ElieNahas** [comment] 2022-06-07 15:42
Hello @Mitcal ,

Concerning the transfer, I tried multiple combinations to transfer the recordings directly to the Scalelite instance from the old server but with no success.

What worked for me is to allocate for the EC2 instance a disk storage (with a predefined size of 750GB) where I was able to transfer the recordings from the old server. I was even able to fetch the recordings using the API of the EC2 instance. To do that I used the following commands for the transfer.

`rsync -rP root@old_server_hostname:/datadrive/bigbluebutton/unpublished/ /var/bigbluebutton/unpublished/`
`rsync -rP root@old_server_hostname:/datadrive/bigbluebutton/recording/raw/ /var/bigbluebutton/recording/raw/`
`rsync -rP root@old_server_hostname:/datadrive/bigbluebutton/published/ /var/bigbluebutton/published/`
`chown -R bigbluebutton:bigbluebutton /var/bigbluebutton/published /var/bigbluebutton/unpublished /var/bigbluebutton/recording/raw`



But the above recordings are only accessible from the EC2 instance not from the Scalelite/Load balancer server APIs. I tried to refer to the following [link](https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md) but I wasn't able to successfully migrate them from the new EC2 to Scalelite.

**Comment by couchgott** [comment] 2022-06-08 07:35
Hi @ElieNahas 

yes it might be hard to get recordings from a single instance to a scaling setup this way. 
the issue might be. you're transferring the media files but you're missing the meeting information containing the related recording metadata which is needed to display recordings within the portal (like greenlight). the app server itself is not needed such infomration. it just displays whatever it finds at it's local storage depending your permissions. 
some ideas about how this can be approached: https://sandstorm.de/de/blog/post/migration-of-greenlight-and-big-blue-button.html 

so you could try to not utilize the DB from the fresh setup but migrate the greenlight database as well. 
within the database you might want to look for the recordings file path and alter this to the new file path structure after migration. it should be doable using a simple query script. 

Best,

David

**Comment by couchgott** [comment] 2022-09-07 07:40
hi @ElieNahas 

sorry for the very late response (i was on sick leave for a long time)
did you manage to get this solved? 

Best, 

David

**Closed** 2022-09-09 10:22 UTC
Labels: question
